# Generated by Django 4.0.3 on 2022-04-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policestation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissioner',
            name='action',
            field=models.BooleanField(default=False),
        ),
    ]
