# Generated by Django 4.0.3 on 2022-04-15 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0018_delete_fir'),
        ('policestation', '0002_commissioner_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('address', models.TextField()),
                ('fir', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('pname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citizen.user')),
                ('solved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policestation.commissioner')),
            ],
        ),
    ]
