# Generated by Django 4.0.3 on 2022-04-15 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0019_delete_complaint'),
        ('policestation', '0003_fir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccname', models.CharField(max_length=50)),
                ('cphone', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('caddress', models.TextField()),
                ('complaint', models.TextField()),
                ('cstatus', models.BooleanField(default=False)),
                ('cpname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citizen.user')),
            ],
        ),
    ]
