# Generated by Django 4.0.3 on 2022-04-15 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policestation', '0004_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iemail', models.EmailField(max_length=254, unique=True)),
                ('ipassowrd', models.CharField(max_length=30)),
                ('iname', models.CharField(max_length=50)),
                ('iphone', models.CharField(max_length=15)),
                ('iarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policestation.fir')),
            ],
        ),
    ]
