# Generated by Django 4.0.3 on 2022-04-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policestation', '0005_inspector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coemail', models.EmailField(max_length=254, unique=True)),
                ('copassword', models.CharField(max_length=30)),
                ('coname', models.CharField(max_length=50)),
                ('cophone', models.CharField(max_length=15)),
                ('coarea', models.CharField(max_length=50)),
            ],
        ),
    ]
