# Generated by Django 4.0.3 on 2022-04-16 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policestation', '0006_constable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspector',
            name='iarea',
        ),
    ]
