# Generated by Django 4.0.3 on 2022-04-18 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policestation', '0008_inspector_iarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='solvedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policestation.commissioner'),
        ),
    ]
