# Generated by Django 4.0.3 on 2022-04-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policestation', '0009_complaint_solvedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manageinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchname', models.CharField(max_length=50)),
                ('branchcode', models.CharField(max_length=10)),
                ('cityname', models.CharField(max_length=50)),
                ('branchphone', models.CharField(max_length=15)),
            ],
        ),
    ]
