# Generated by Django 4.0.3 on 2022-04-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policestation', '0010_manageinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='photo'),
        ),
    ]
