# Generated by Django 4.0.3 on 2022-04-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('Gujarat', 'Gujarat'), ('Maharastra', 'Maharastra'), ('U.P', 'U.P'), ('M.P', 'M.P'), ('A.P', 'A.P')], max_length=50)),
            ],
        ),
    ]
