# Generated by Django 4.0.3 on 2022-04-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_rename_username_user_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('cname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('adress', models.TextField()),
                ('fir', models.TextField()),
            ],
        ),
    ]
