# Generated by Django 4.0.3 on 2022-04-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0004_alter_fir_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fir',
            old_name='adress',
            new_name='address',
        ),
    ]
