# Generated by Django 4.0.3 on 2022-04-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0005_rename_adress_fir_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpname', models.CharField(max_length=50)),
                ('ccname', models.CharField(max_length=50)),
                ('cphone', models.CharField(max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('caddress', models.TextField()),
                ('complaint', models.TextField()),
            ],
        ),
    ]
