# Generated by Django 4.0.3 on 2022-04-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0006_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpname', models.CharField(max_length=30)),
                ('fphone', models.CharField(max_length=20)),
                ('feedback', models.TextField()),
            ],
        ),
    ]
