# Generated by Django 4.0.3 on 2022-04-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0007_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fir',
            name='pname',
        ),
    ]
