# Generated by Django 4.0.3 on 2022-04-11 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0008_remove_fir_pname'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='pname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citizen.user'),
        ),
    ]
