# Generated by Django 4.0.3 on 2022-04-11 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0010_alter_complaint_cpname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='cpname',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.RemoveField(
            model_name='fir',
            name='pname',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='Fir',
        ),
    ]
