# Generated by Django 4.0.3 on 2022-04-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0012_feedback_fir_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
