# Generated by Django 4.0.3 on 2022-04-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0014_complaint_csatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='csatus',
            field=models.BooleanField(default=False),
        ),
    ]
