# Generated by Django 4.0.3 on 2022-04-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0015_alter_complaint_csatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='csatus',
            new_name='cstatus',
        ),
    ]
