# Generated by Django 4.0.3 on 2022-04-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0017_fir_solved_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fir',
        ),
    ]
