# Generated by Django 4.0.3 on 2022-04-15 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0018_delete_fir'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
